language: node_js

node_js:
  - 9
  - 8

cache:
  directories:
    - node_modules
    - $HOME/.meteor/

before_install:
  - export PATH="$HOME/.meteor:$PATH"
  - curl https://install.meteor.com | /bin/sh

before_script:
  - npm install

script:
  - npm run cli